services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
